"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-writer' references
in its source tree. Renames or moves in peer standalones (or in the
umbrella's deep-import surface) surface as a hard failure here — not
as a silent ModuleNotFoundError when an end user runs the CLI.
"""
import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex.clew',
    'scitex_app._django',
    'scitex_app._standalone',
    'scitex_dev._cli._completion',
    'scitex_dev.cli',
    'scitex_dev.decorators',
    'scitex_dev.skills',
    'scitex_dev.types',
    'scitex_scholar',
    'scitex_ui',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-writer's declared cross-package dependency must succeed."""
    importlib.import_module(module_name)
