"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-writer' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Module NOT installed (peer standalone absent in the CI env) →
  test is SKIPPED via `pytest.importorskip`. The umbrella's CI
  (which installs every peer) catches cross-package renames.
"""

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    # Peer standalones — these are true cross-package deps. If one of these
    # modules is renamed/moved in a peer package, this test fails loudly.
    "scitex_app._django",
    "scitex_app._standalone",
    "scitex_clew",
    "scitex_dev",
    "scitex_dev._cli._completion",
    "scitex_dev.cli",
    "scitex_dev.decorators",
    "scitex_dev.skills",
    "scitex_dev.types",
    "scitex_scholar",
    "scitex_ui",
    # Self-imports — also listed here because the audit derives the package
    # name from the repo directory basename, which is "/work" in CI containers
    # rather than "scitex-writer". Including them is harmless: they exercise
    # the package's own module tree and always pass when the package is
    # installed.
    "scitex_writer",
    "scitex_writer._ports",
    "scitex_writer._ports.thumbnails",
    "scitex_writer._ports.workspace",
    "scitex_writer._server",
    "scitex_writer.figures",
    "scitex_writer.tables",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-writer's declared cross-package dependency must succeed."""
    # Arrange
    # Act
    module = pytest.importorskip(module_name)
    # Assert
    assert module is not None
