"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    try:
        audit_all_for_package(
            "scitex-writer",
            skip_rules=(
                "PS201",  # parent tests-dir mirror — empty placeholder dirs would
                "PS202",  # trade PS202 for PS207; deferred until each src dir gets real tests
                "PS503",  # examples/03_python_api fails to reach FINISHED_SUCCESS
                # because of an upstream scitex-session KeyError in setup_matplotlib
            ),
        )
    except TypeError:
        pytest.xfail("PS201/PS202 deferred; needs scitex-dev>=0.11.3 for skip_rules")
