"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""

import shutil

import pytest


def test_audit_all_clean():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    try:
        audit_all_for_package(
            "scitex-writer",
            skip_rules=(
                "PS201",  # parent tests-dir mirror — empty placeholder dirs
                "PS202",  # trade PS202 for PS207; per-src-dir tests pending
                "PS503",  # examples/03_python_api FINISHED_SUCCESS blocked by
                # upstream scitex-session KeyError in setup_matplotlib
                "§1",  # umbrella bridge — fires when umbrella scitex is
                # transitively installed; lives in scitex-python repo
                "§6",  # MCP/Python-API parity — demoted to warn upstream
                # (scitex-dev develop, post-v0.11.6); pin will catch up
            ),
        )
    except TypeError:
        pytest.xfail("skip_rules requires scitex-dev>=0.11.3")
