#!/bin/bash
# -*- coding: utf-8 -*-
# ROLE: engine-vendored — DO NOT edit here. `scitex-writer update-project`
# overwrites this file on every re-vendor; fix it upstream in the
# scitex-writer package instead (local edits are lost, and update-project
# may set it read-only in the consumer workspace after vendoring).
# File: ./scripts/shell/modules/usage_manuscript.sh
#
# The `--help` text of compile_manuscript.sh, extracted so the orchestrator
# stays about ORCHESTRATION. Sourced by compile_manuscript.sh, which defines
# the colors ($GRAY/$BOLD_CYAN/$GREEN/$YELLOW/$NC) and $PROJECT_ROOT this
# function reads at call time.

usage() {
    echo ""
    echo -e "${BOLD_CYAN}━━━ compile_manuscript.sh ━━━${NC}"
    echo -e "${GRAY}Compile main manuscript document${NC}"
    echo ""
    echo -e "${BOLD_CYAN}━━━ Structure ━━━${NC}"
    echo -e "  ${GREEN}01_manuscript/${NC}"
    echo -e "    contents/"
    echo -e "      ${YELLOW}abstract.tex${NC}        ${GRAY}# Abstract${NC}"
    echo -e "      ${YELLOW}introduction.tex${NC}    ${GRAY}# Introduction${NC}"
    echo -e "      ${YELLOW}methods.tex${NC}         ${GRAY}# Methods${NC}"
    echo -e "      ${YELLOW}results.tex${NC}         ${GRAY}# Results${NC}"
    echo -e "      ${YELLOW}discussion.tex${NC}      ${GRAY}# Discussion${NC}"
    echo -e "      figures/caption_and_media/  ${GRAY}# Figures${NC}"
    echo -e "      tables/caption_and_media/   ${GRAY}# Tables${NC}"
    echo -e "    ${GRAY}manuscript.pdf${NC}      ${GRAY}# Output${NC}"
    echo ""
    echo -e "${BOLD_CYAN}━━━ Editable Files ━━━${NC}"
    echo -e "${GREEN}00_shared:${NC}"
    echo -e "  ${GRAY}$PROJECT_ROOT/00_shared/${NC}title.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/00_shared/${NC}authors.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/00_shared/${NC}keywords.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/00_shared/${NC}journal_name.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/00_shared/bib_files/${NC}*.bib"
    echo ""
    echo -e "${GREEN}01_manuscript:${NC}"
    echo -e "  ${GRAY}$PROJECT_ROOT/01_manuscript/contents/${NC}abstract.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/01_manuscript/contents/${NC}introduction.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/01_manuscript/contents/${NC}methods.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/01_manuscript/contents/${NC}results.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/01_manuscript/contents/${NC}discussion.tex"
    echo -e "  ${GRAY}$PROJECT_ROOT/01_manuscript/contents/figures/${NC}caption_and_media/"
    echo -e "  ${GRAY}$PROJECT_ROOT/01_manuscript/contents/tables/${NC}caption_and_media/"
    echo ""
    echo -e "${BOLD_CYAN}━━━ Options ━━━${NC}"
    echo "  -nf,  --no_figs       Skip figure processing (~4s faster)"
    echo "  -nt,  --no_tables     Skip table processing (~4s faster)"
    echo "  -nd,  --no_diff       Skip diff generation (~17s faster)"
    echo "  -d,   --draft         Single-pass compilation (~5s faster)"
    echo "  -dm,  --dark_mode     Dark mode: black background, white text"
    echo "  -p2t, --ppt2tif       Convert PowerPoint to TIF (WSL)"
    echo "  -c,   --crop_tif      Crop TIF whitespace"
    echo "  -q,   --quiet         Minimal output"
    echo "  --force               Force full recompilation"
    echo "  --clew-overlay        Color \\vclaim values by clew provenance status"
    echo "  -h,   --help          Show this help"
    echo ""
    echo -e "${GRAY}Note: Options accept both hyphens and underscores${NC}"
    echo ""
    echo -e "${BOLD_CYAN}━━━ Document Structure (base.tex) ━━━${NC}"
    echo -e "  ${GRAY}$PROJECT_ROOT/01_manuscript/${NC}base.tex"
    echo -e "  Controls section order via \\\\input{} commands:"
    echo -e "    ${GRAY}% \\\\input{./01_manuscript/contents/${NC}highlights${GRAY}}${NC}  ${GRAY}# Commented out (optional)${NC}"
    echo -e "    ${GRAY}\\\\input{./01_manuscript/contents/${NC}title${GRAY}}${NC}"
    echo -e "    ${GRAY}\\\\input{./01_manuscript/contents/${NC}authors${GRAY}}${NC}"
    echo -e "    ${GRAY}\\\\input{./01_manuscript/contents/${NC}abstract${GRAY}}${NC}"
    echo -e "    ${GRAY}\\\\input{./01_manuscript/contents/${NC}keywords${GRAY}}${NC}"
    echo -e "    ${GRAY}\\\\input{./01_manuscript/contents/${NC}introduction${GRAY}}${NC}"
    echo -e "    ${GRAY}\\\\input{./01_manuscript/contents/${NC}methods${GRAY}}${NC}"
    echo -e "    ${GRAY}\\\\input{./01_manuscript/contents/${NC}results${GRAY}}${NC}"
    echo -e "    ${GRAY}\\\\input{./01_manuscript/contents/${NC}discussion${GRAY}}${NC}"
    echo -e "  To add/remove sections: edit base.tex \\\\input{} lines"
    echo -e "  Comment out with %% to disable a section"
    echo ""
    echo -e "${BOLD_CYAN}━━━ Adding Figures ━━━${NC}"
    echo -e "  ${GREEN}Location:${NC} ${YELLOW}01_manuscript/contents/figures/caption_and_media/${NC}"
    echo -e "  ${GREEN}Supported:${NC} PNG, JPEG, PDF, SVG, TIFF, Mermaid (.mmd)"
    echo ""
    echo -e "  ${GREEN}Naming Rule:${NC} Prefix with 2-digit number for ordering"
    echo -e "    ${YELLOW}01_my_figure.png${NC}  ${GRAY}# Media file${NC}"
    echo -e "    ${YELLOW}01_my_figure.tex${NC}  ${GRAY}# Caption file (same base name)${NC}"
    echo ""
    echo -e "  ${GREEN}Caption File Format:${NC}"
    echo -e "    ${GRAY}%% Figure caption${NC}"
    echo -e "    ${GRAY}\\\\caption{Your caption here.}${NC}"
    echo -e "    ${GRAY}\\\\label{fig:my_figure_01}${NC}"
    echo ""
    echo -e "  ${GREEN}Citing in Text:${NC} Use ${YELLOW}\\\\ref{fig:my_figure_01}${NC} or ${YELLOW}Figure~\\\\ref{fig:my_figure_01}${NC}"
    echo ""
    echo -e "${BOLD_CYAN}━━━ Adding Tables ━━━${NC}"
    echo -e "  ${GREEN}Location:${NC} ${YELLOW}01_manuscript/contents/tables/caption_and_media/${NC}"
    echo -e "  ${GREEN}Format:${NC} CSV auto-converts to LaTeX table"
    echo ""
    echo -e "  ${GREEN}Naming Rule:${NC} Prefix with 2-digit number for ordering"
    echo -e "    ${YELLOW}01_my_table.csv${NC}   ${GRAY}# Data file (CSV format)${NC}"
    echo -e "    ${YELLOW}01_my_table.tex${NC}   ${GRAY}# Caption file (same base name)${NC}"
    echo ""
    echo -e "  ${GREEN}Caption File Format:${NC}"
    echo -e "    ${GRAY}%% Table caption${NC}"
    echo -e "    ${GRAY}\\\\caption{Your caption here.}${NC}"
    echo -e "    ${GRAY}\\\\label{tab:my_table_01}${NC}"
    echo ""
    echo -e "  ${GREEN}Citing in Text:${NC} Use ${YELLOW}\\\\ref{tab:my_table_01}${NC} or ${YELLOW}Table~\\\\ref{tab:my_table_01}${NC}"
    echo ""
    echo -e "${BOLD_CYAN}━━━ Managing Bibliography ━━━${NC}"
    echo -e "  Place .bib files in: ${YELLOW}$PROJECT_ROOT/00_shared/bib_files/${NC}"
    echo -e "  Multiple .bib files auto-merge with deduplication"
    echo -e "  Citation style: ${YELLOW}$PROJECT_ROOT/config/config_manuscript.yaml${NC}"
    echo -e "  Styles: ${GREEN}unsrtnat${NC}, ${GREEN}plainnat${NC}, ${GREEN}apalike${NC}, ${GREEN}IEEEtran${NC}, ${GREEN}naturemag${NC}"
    echo ""
    exit 0
}

# EOF
