#!/bin/bash
# -*- coding: utf-8 -*-
# File: scripts/maintenance/show_usage.sh
# Description: Display project usage guide

# Resolve project root
THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$THIS_DIR/../.." && pwd)"

echo ""
echo "╭────────────────────────────────────────────────────────────────╮"
echo "│  SciTeX Writer - Project Usage Guide                           │"
echo "╰────────────────────────────────────────────────────────────────╯"
echo ""
echo "Project Root: $PROJECT_ROOT"
echo ""
echo "Editable Content:"
echo "  $PROJECT_ROOT/00_shared/title.tex"
echo "  $PROJECT_ROOT/00_shared/authors.tex"
echo "  $PROJECT_ROOT/00_shared/keywords.tex"
echo "  $PROJECT_ROOT/00_shared/journal_name.tex"
echo "  $PROJECT_ROOT/00_shared/bib_files/*.bib"
echo ""
echo "  $PROJECT_ROOT/01_manuscript/contents/abstract.tex"
echo "  $PROJECT_ROOT/01_manuscript/contents/introduction.tex"
echo "  $PROJECT_ROOT/01_manuscript/contents/methods.tex"
echo "  $PROJECT_ROOT/01_manuscript/contents/results.tex"
echo "  $PROJECT_ROOT/01_manuscript/contents/discussion.tex"
echo "  $PROJECT_ROOT/01_manuscript/contents/figures/caption_and_media/"
echo "  $PROJECT_ROOT/01_manuscript/contents/tables/caption_and_media/"
echo ""
echo "Project Structure:"
echo "  00_shared/           Shared: title, authors, keywords, journal_name, bib_files/"
echo "  01_manuscript/       Main manuscript (abstract, intro, methods, results, discussion)"
echo "  02_supplementary/    Supplementary materials (methods, results, figures, tables)"
echo "  03_revision/         Revision responses (editor/, reviewer1/, reviewer2/)"
echo ""
echo "Compilation Scripts:"
echo "  ./compile.sh manuscript       Compile main manuscript"
echo "  ./compile.sh supplementary    Compile supplementary materials"
echo "  ./compile.sh revision         Compile revision responses"
echo ""
echo "Script Options:"
echo "  --no-figs        Skip figure processing (faster compilation)"
echo "  --no-tables      Skip table processing"
echo "  --no-diff        Skip diff generation (saves ~10s)"
echo "  --draft          Single-pass compilation (saves ~5s)"
echo "  --quiet          Suppress verbose output"
echo "  --verbose        Show detailed logs"
echo "  --dark-mode      Black background, white text"
echo ""
echo "Quick Examples:"
echo "  ./compile.sh manuscript                    # Full compilation"
echo "  ./compile.sh manuscript --draft --no-diff  # Fast draft mode"
echo "  make manuscript                            # Via Makefile"
echo ""
echo "For more details: make help"
echo ""

# EOF
